import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import ReduxProvider from "@/lib/redux/provider";
import { ReactNode } from "react";
import "./globals.css";
import { Header } from "@/components/header";
import { TabName } from "@/lib/types";

const lexendDeca = Lexend_Deca({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
  searchParams: { tab: TabName; theme: string };
}) {
  return (
    <html lang="en">
      <body className={lexendDeca.className}>
        <ReduxProvider>
          <div className="absolute inset-0 bg-slate-50 overflow-hidden text-black">
            <Header />
            <div className={"h-[99%] overflow-hidden"}>{children}</div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
