import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import ReduxProvider from "@/lib/redux/provider";
import { ReactNode } from "react";
import "./globals.css";

const lexendDeca = Lexend_Deca({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={lexendDeca.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
